name: 'Run python unit tests'

on: [push]

env:
  FLASK_ENV: production
  FLASK_DEBUG: 1
  FLASK_APP: son
  LOG_LEVEL: DEBUG
  TEST_URL: http://localhost:8080
  SECRET_KEY: ef987sd9fwkjefosf9we0svs9q3evsd0

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      #- name: Lint with flake8
      #  run: |
      #    # stop the build if there are Python syntax errors or undefined names
      #    flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
      #    # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
      #    flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      #    sudo -u postgres createdb son
      #    flask db stamp head
      #    flask db init

      - name: Install Playwright and browsers
        run: |
          pip install playwright pytest-playwright asyncio
          pip install -e .
          python -m playwright install --with-deps

      - name: Start site
        run: |
          waitress-serve --call 'son:create_app' &

      - name: Test with pytest
        run: |
          pytest -s --show-capture=all
